Adding the compatibility of graph patterns for the grammar
frink-okn/SPARQL.js pull request #4
Opened 2024-07-22 19:29 UTC by psvkaushik

2024-07-23 17:33 UTC, balhoff requested changes

2024-07-23 17:33 UTC, balhoff commented on index.d.ts
> +    value: IriTerm | GraphPattern;
Needs to be optional.

2024-07-23 17:33 UTC, balhoff commented on index.d.ts
> +    value: IriTerm | Var | GraphPattern;
```suggestion
    value: Var | PropertyPath | Pattern[];
```

2024-07-23 17:33 UTC, balhoff commented on lib/sparql.jison
> +    : 'START' Var '=' PathStartValue
`PathValue` right? Also `= PathValue` should be optional.

2024-07-23 17:33 UTC, balhoff commented on lib/sparql.jison
> +    | 'END'  Var '=' PathEndValue
`PathValue` right? Also `= PathValue` should be optional.

2024-07-23 17:33 UTC, balhoff commented on index.d.ts
> +    value: IriTerm | Var | GraphPattern;
I changed `GraphPattern` to `Pattern[]`, based on looking at what was used for `WHERE`. Pretty sure `GraphPattern` is for specifying a named graph.

2024-07-23 17:34 UTC, balhoff commented
Would be good to add tests!

2024-07-23 22:24 UTC, psvkaushik commented
- Made the values of Start, End, and Via to be optional. Will include the test cases in the next commit.

2024-08-05 15:28 UTC, merged

2024-08-05 16:20 UTC, balhoff reviewed
@psvkaushik I think there are a couple of issues with this interface. Can you make another PR?

2024-08-05 16:20 UTC, balhoff commented on index.d.ts
> +    value: IriTerm | Pattern[];
@psvkaushik shouldn't this be optional? An IRI or a pattern can be supplied but it isn't necessary.

2024-08-05 16:20 UTC, balhoff commented on index.d.ts
> +}
This should just be var or iri or pattern. I don't think you need this structure.